### ISSUE TITLE
Missing config.json file

### ISSUE THREAD

**Issue by DiogoVidevince** [huggingface/distil-whisper#10]
I am trying to run the following code:

```python
import torch
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, pipeline
from datasets import load_dataset


device = "cuda:0" if torch.cuda.is_available() else "cpu"
torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32

model_id = "distil-whisper/distil-large-v2"

model = AutoModelForSpeechSeq2Seq.from_pretrained(
    model_id, torch_dtype=torch_dtype, low_cpu_mem_usage=True, use_safetensors=True
)
```

But I am getting the following error:

```terminal
OSError: distil-whisper/distil-large-v2 does not appear to have a file named config.json. Checkout 'https://huggingface.co/distil-whisper/distil-large-v2/main' for available files.
```

Am I doing something wrong?

Btw, the `distil-whisper` instructions says `Distil-Whisper is supported in Hugging Face Transformers from version 4.35 onwards`, but I wasn't able to find that version: [https://pypi.org/project/transformers/#history](https://pypi.org/project/transformers/#history)

**Comment by AnkushMalaker** [comment]
Model not uploaded yet I believe. The repo that the model links to, at this moment infact doesn't have config.json as the error suggests.

**Comment by kristiankielhofner** [comment]
It's fairly common for "bleeding edge" stuff to need to install transformers from git main:

`pip install git+https://github.com/huggingface/transformers`

This shows version transformers-4.35.0.dev0 currently.

**Comment by DiogoVidevince** [comment]
> Model not uploaded yet I believe. The repo that the model links to, at this moment infact doesn't have config.json as the error suggests.

That makes sense. It seems like they have updated this repo here before updating the model

**Comment by sanchit-gandhi** [comment]
Hey @DiogoVidevince - the models will be available in 2-3 hours time! Thanks for your patience!

**Comment by sanchit-gandhi** [comment]
Models are up! Please see the [usage section](https://github.com/huggingface/distil-whisper#1-usage) of the README for detailed code examples. Feel free to open a new issue if you experience any problems!
