### ISSUE TITLE
Repository Not Found for url

### ISSUE THREAD

**Issue by wailokkwok** [huggingface/distil-whisper#136]
I am facing this error

Repository Not Found for url: https://huggingface.co/api/models/jythjfjfh/common_voice_16_1_hi_pseudo_labelled/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

This is the terminal command I am running

python3 run_pseudo_labelling.py --model_name_or_path "openai/whisper-large-v3" --dataset_name "mozilla-foundation/common_voice_16_1" --dataset_config_name "hi" --dataset_split_name "train+validation+test" --text_column_name "sentence" --id_column_name "path" --output_dir "./common_voice_16_1_hi_pseudo_labelled" --wandb_project "distil-whisper-labelling" --per_device_eval_batch_size 1 --dtype "bfloat16" --attn_implementation sdpa --logging_steps 500 --max_label_length 256 --concatenate_audio True --preprocessing_batch_size 1 --preprocessing_num_workers 4 --dataloader_num_workers 4 --report_to "wandb" --language "hi" --task "transcribe" --return_timestamps True --streaming False --generation_num_beams 1 --push_to_hub

**Comment by marziye-A** [comment]
did you find any solution?
I face the same issue.

**Comment by zbowen0225** [comment]
I also met this problem. How to solve it? 
I just remove the --push_to_hubb label. But this is not a proper solution...

**Comment by DesouzaSherwin** [comment]
How was this issue solved?
