### ISSUE TITLE
Is it possible to run the model to recognize other languages?

### ISSUE THREAD

**Issue by sanek11591** [huggingface/distil-whisper#15]
Can this model be used for other languages ​​and if so, how?

**Comment by sanchit-gandhi** [comment]
Currently English-only with a multilingual release planned, _c.f._ https://github.com/huggingface/distil-whisper/issues/6#issuecomment-1790869897

**Comment by sanchit-gandhi** [comment]
Closing as this is a duplicate of https://github.com/huggingface/distil-whisper/issues/6#issuecomment-1790869897!
