### ISSUE TITLE
is it possible to train it with own dataset for kazakh language?

### ISSUE THREAD

**Issue by diasbalmash** [huggingface/distil-whisper#21]
Suppose I have a large dataset in kazakh language. So, can I use this approach to train model in kazakh language?

**Comment by sanchit-gandhi** [comment]
Yes! We'll be releasing training code this week which will generalise to all languages Whisper was pre-trained on (and likely also those it wasn't 👀)

**Comment by diasbalmash** [comment]
@sanchit-gandhi thank yoy for info

**Comment by sanchit-gandhi** [comment]
Training code released under this folder: https://github.com/huggingface/distil-whisper/tree/main/training
