### ISSUE TITLE
How long of an Audio Clip can the model transcribe at once?

### ISSUE THREAD

**Issue by Aryan-401** [huggingface/distil-whisper#34]
I've tried various audio clips, and the maximum I've gotten the model to transcribe is 30 seconds, is there any way to make the transcriptions longer?

**Comment by sanchit-gandhi** [comment]
Indeed, you can use the long-form transcription algorithm as specified in the README: https://github.com/huggingface/distil-whisper#long-form-transcription

**Comment by Aryan-401** [comment]
Got it to work after upgrading transformers, Thanks!
