### ISSUE TITLE
Smaller models?

### ISSUE THREAD

**Issue by regularfry** [huggingface/distil-whisper#35]
Unless I've missed something, it's not clear whether the same technique works to accelerate the `small.en` and smaller whisper models.  Is that something you've looked at?  If not, would there be any mileage in training it up?

`small.en` in particular is interesting because it's the biggest that fits onto a raspberry pi zero 2, but isn't quite fast enough for realtime use.  Speeding it up would be transformative.

**Comment by sanchit-gandhi** [comment]
See #14 for a discussion on distilling smaller models. The technique should indeed work, and we are in the process of distilling `small.en`!

**Comment by sanchit-gandhi** [comment]
Training code released under this folder in case you want to try yourself! https://github.com/huggingface/distil-whisper/tree/main/training

**Comment by sanchit-gandhi** [comment]
Here you go! https://huggingface.co/distil-whisper/distil-small.en

**Comment by regularfry** [comment]
Thanks! I'll open a separate issue, but it's considerably slower than the original small.en on my M1 under whisper.cpp.  That's deeply unintuitive to me, and it's not clear to me where the problem might be.
