### ISSUE TITLE
Is this supposed to support large-v3?

### ISSUE THREAD

**Issue by captainyugi00** [huggingface/distil-whisper#36]
Hello, is this model supporting large-v3?

**Comment by sanchit-gandhi** [comment]
Distilling `large-v3` now! It's a ~2 week process if you include pseudo-labelling the data and training the model

**Comment by salahzoubi** [comment]
@sanchit-gandhi will batch transcribe be supported like it is supported in large v3?

**Comment by rawwerks** [comment]
> Distilling `large-v3` now! It's a ~2 week process if you include pseudo-labelling the data and training the model

This will change the game! Especially once @ggerganov gets his hands on it (.cpp)

**Comment by timchenxiaoyu** [comment]
wait

**Comment by sanchit-gandhi** [comment]
Running `distil-large-v3` with some updates that will mean better long-form WER performance using OpenAI's long-form algorithm. This should also translate to WER improvements in other libraries like `faster-whisper` and Whisper cpp!

Training run logs: https://wandb.ai/sanchit-gandhi/distil-whisper?workspace=user-sanchit-gandhi

**Comment by Mijawel** [comment]
Is distil-large-v3 finished?

**Comment by v3ss0n** [comment]
When distill largev3?

**Comment by hlevring** [comment]
Good things take a little time ;)

**Comment by sanchit-gandhi** [comment]
I'd say ETA is about 1-2 weeks. Getting really promising long-form WER results now (within 1.3% WER of large-v3 using OpenAI's long-form transcription algorithm) - currently training the model so that it works with `condition_on_prev_text`

**Comment by qwopqwop200** [comment]
Does Distill Large v3 support multilingual, or does it only support English?

**Comment by AiDreamerOoO** [comment]
> 我想说预计到达时间约为 1-2 周。现在获得了真正有希望的长格式 WER 结果（使用 OpenAI 的长格式转录算法，WER 在大型 v3 的 1.3% 以内） - 目前正在训练模型，以便它可以与`condition_on_prev_text`

加油

**Comment by GeorgesLeYeti** [comment]
Any news on largeV3 ?

**Comment by MrRace** [comment]
Wish

**Comment by solaoi** [comment]
great work! thx
https://huggingface.co/distil-whisper/distil-large-v3
