### ISSUE TITLE
Streaming Implementation of Distil Whisper

### ISSUE THREAD

**Issue by souvikqb** [huggingface/distil-whisper#41]
Is it possible to use Distil Whisper for streaming applications? 

Can I send small chunks of audio files to a server for processing?

Use Case - I wish to use my mic to send small chunks of audio files to a server and process them quickly to get back the transcripts

**Comment by aleksandr-smechov** [comment]
Try these gists:

client-side code: https://gist.github.com/c789caa0b65772865a3dc1e60e0f2c5d.git

server-size code: https://gist.github.com/f9a223ff62521c1644469b3505308d45.git

You can run both on the same machine with `python script_name.py`.

**Comment by sanchit-gandhi** [comment]
Here's a version that runs locally that you can adapt: https://github.com/huggingface/distil-whisper/issues/4#issuecomment-1794494419

**Comment by sanchit-gandhi** [comment]
Going to close this and encourage the discussion be kept on the original issue! Feel free to comment there if you have any issues!
