### ISSUE TITLE
Distillation code and calibration data

### ISSUE THREAD

**Issue by vgoklani** [huggingface/distil-whisper#5]
Are you planning to release the distillation code and calibration data?

**Comment by sanchit-gandhi** [comment]
Yes! We will release training code to reproduce the model in PyTorch and JAX next week

**Comment by GuoYi0** [comment]
please, please, please... My dear, training code is urgently needed...

**Comment by JinYu1998** [comment]
> Yes! We will release training code to reproduce the model in PyTorch and JAX next week是的！我们将在下周发布训练代码，以在 PyTorch 和 JAX 中重现模型

How is the release progressing, really need to read and learn this code urgently. Tks!

**Comment by sanchit-gandhi** [comment]
Training code released under this folder in JAX and PyTorch: https://github.com/huggingface/distil-whisper/tree/main/training
