### ISSUE TITLE
Can fine tuning for phoneme task?

### ISSUE THREAD

**Issue by jackNhat** [huggingface/distil-whisper#57]
Has anyone experimented with fine-tuning the phoneme recognition task (English), please share some of your experiments. 
Many thanks !

**Comment by sanchit-gandhi** [comment]
I haven't personally, but would be interested to know if anyone has tried this. Note that the Whisper tokenizer does not contain phoneme tokens, so the model will require a new tokenizer to be trained and subsequently the vocabulary size to be adjusted (_c.f._ https://huggingface.co/docs/transformers/v4.18.0/en/model_doc/wav2vec2_phoneme#transformers.Wav2Vec2PhonemeCTCTokenizer)
