### ISSUE TITLE
The evaluation stuck after unwrap_model during distillation training

### ISSUE THREAD

**Issue by HackGiter** [huggingface/distil-whisper#69]
![image](https://github.com/huggingface/distil-whisper/assets/50295237/c667b42d-7161-4e12-bf29-0e55a41059ba)
![image](https://github.com/huggingface/distil-whisper/assets/50295237/28d82152-d8a4-4f28-b501-b8066814193f)
Should I add accelerator.prepare after unwarp?

**Comment by sanchit-gandhi** [comment]
Hey @HackGiter! Sorry for the delay here - resolved in #74! Let me know if you encounter any other issues - best of luck with your distillation efforts!
