### ISSUE TITLE
Where is the model?

### ISSUE THREAD

**Issue by lkmdhertg** [huggingface/distil-whisper#8]
Link to HF leads to empty files section.

**Comment by asdkazmi** [comment]
The model is expected to be published by 2nd November US time. So, there are few hours remaining yet, tik tik tik...

**Comment by sanchit-gandhi** [comment]
Models will be released on the Hub in 2-3 hours time!

**Comment by sanchit-gandhi** [comment]
Models are up! Please see the [usage section](https://github.com/huggingface/distil-whisper#1-usage) of the README for detailed code examples. Feel free to open a new issue if you experience any problems!
