### ISSUE TITLE
distil-small.en AttributeError 

### ISSUE THREAD

**Issue by andrewjones0198** [huggingface/distil-whisper#90]
Followed steps provided in the following URL:

https://huggingface.co/distil-whisper/distil-small.en

pip-24.0 used to install  transformers-4.38.1-py3-none-any.whl.metadata using python 3.12.1 in venv

distil-large-v2 runs with no issues however distil-small.en displays the following error:

AttributeError: 'GenerationConfig' object has no attribute 'lang_to_id' 

Any ideas on how to solve? Much appreciated for any assistance provided

**Comment by dulalbert** [comment]
Same for distil-medium.en, I just used the large version

**Comment by andrewjones0198** [comment]
If size of the model is a concern then I have found the following worked for me:

https://huggingface.co/openai/whisper-tiny.en

There are a few models available with tiny.en being the smallest.

This ran with sub 3 second latency once the model built on my NUC style device.
